### ISSUE TITLE
packages not in the dependency graph for a given target lead to panics

### ISSUE THREAD

**Issue by froydnj** [sfackler/cargo-tree#44]
Attempting to find dependencies of a particular package in Firefox's repository from an x86-64 Linux machine gives:

```
froydnj@hawkeye:~/src/gecko-dev.git$ RUST_BACKTRACE=1 cargo tree --manifest-path `pwd`/toolkit/library/rust/Cargo.toml -p winapi:0.2.8 --invert
thread 'main' panicked at 'no entry found for key', libcore/option.rs:960:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::option::expect_failed
             at libcore/option.rs:960
   9: <std::collections::hash::map::HashMap<K, V, S> as core::ops::index::Index<&'a Q>>::index
  10: cargo_tree::print_tree
  11: cargo_tree::real_main
  12: cargo_tree::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  17: main
  18: __libc_start_main
  19: _start
```

The problem seems to be that `winapi 0.2.8` is only used on Windows targets:

```
froydnj@hawkeye:~/src/gecko-dev.git$ RUST_BACKTRACE=1 cargo tree --manifest-path `pwd`/toolkit/library/rust/Cargo.toml -p winapi:0.2.8 --target i686-pc-windows-msvc --invert
winapi v0.2.8
├── atty v0.2.2
│   └── env_logger v0.5.6
│       ├── gkrust-shared v0.1.0 (file:///home/froydnj/src/gecko-dev.git/toolkit/library/rust/shared)
│       │   └── gkrust v0.1.0 (file:///home/froydnj/src/gecko-dev.git/toolkit/library/rust)
│       └── stylo_tests v0.0.1 (file:///home/froydnj/src/gecko-dev.git/servo/ports/geckolib/tests)
│           [dev-dependencies]
│           └── gkrust v0.1.0 (file:///home/froydnj/src/gecko-dev.git/toolkit/library/rust) (*)
├── kernel32-sys v0.2.2
│   ├── atty v0.2.2 (*)
│   └── parking_lot_core v0.2.7
│       └── parking_lot v0.6.3
│           ├── geckoservo v0.0.1 (file:///home/froydnj/src/gecko-dev.git/servo/ports/geckolib)
│           │   └── stylo_tests v0.0.1 (file:///home/froydnj/src/gecko-dev.git/servo/ports/geckolib/tests) (*)
│           └── style v0.0.1 (file:///home/froydnj/src/gecko-dev.git/servo/components/style)
│               ├── geckoservo v0.0.1 (file:///home/froydnj/src/gecko-dev.git/servo/ports/geckolib) (*)
│               └── stylo_tests v0.0.1 (file:///home/froydnj/src/gecko-dev.git/servo/ports/geckolib/tests) (*)
├── parking_lot_core v0.2.7 (*)
└── u2fhid v0.2.0 (file:///home/froydnj/src/gecko-dev.git/dom/webauthn/u2f-hid-rs)
    └── gkrust-shared v0.1.0 (file:///home/froydnj/src/gecko-dev.git/toolkit/library/rust/shared) (*)
```

Which is understandable, but it would be good to give a better error message than panicking.

**Comment by sfackler** [comment]
Fixed by #54
